version: '3.7'
services:
  sgdb:
    image: postgres:11
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    ports:
      - "54322:5432"
    volumes:
      - ./tmp/sgdb:/var/lib/postgresql/data
  app_rails:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app_rails
    ports:
      - "3000:3000"
    depends_on:
      - sgdb
    links:
      - sgdb